version: "3.8"

services:
  mysql:
    image: mysql:8.4
    container_name: cliplink-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: urlshortenerdb
      MYSQL_USER: clipuser
      MYSQL_PASSWORD: clip123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  cliplink:
    build: .
    container_name: cliplink-app
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXP: ${JWT_EXP}


volumes:
  mysql_data: