spring.application.name=url-shortener-sb
spring.datasource.url=jdbc:mysql://localhost:3306/urlshortenerdb
spring.datasource.username=root
spring.datasource.password=Swastik@2005
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=SYQFY1IWTpa9PWn6OZ9mbO6OzOAEGVWHQAujvCUxW0I=
jwt.expirations=172800000